/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_spectre_Spectre */

#ifndef _Included_android_spectre_Spectre
#define _Included_android_spectre_Spectre
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_spectre_Spectre
 * Method:    nativeCreate
 * Signature: (I)I
 */
JNIEXPORT jlong JNICALL Java_android_spectre_Spectre_nativeCreate
  (JNIEnv *, jclass, jint);

/*
 * Class:     android_spectre_Spectre
 * Method:    nativeDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_android_spectre_Spectre_nativeDestroy
  (JNIEnv *, jclass, jlong);

/*
 * Class:     android_spectre_Spectre
 * Method:    nativeReadPtr
 * Signature: (JJILandroid/spectre/Spectre/Callback;)V
 */
JNIEXPORT void JNICALL Java_android_spectre_Spectre_nativeReadPtr
  (JNIEnv *, jclass, jlong, jlong, jint, jobject);

/*
 * Class:     android_spectre_Spectre
 * Method:    nativeReadBuf
 * Signature: (J[BLandroid/spectre/Spectre/Callback;)V
 */
JNIEXPORT void JNICALL Java_android_spectre_Spectre_nativeReadBuf
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     android_spectre_Spectre
 * Method:    nativeCalibrateTiming
 * Signature: (JI[I[I)I
 */
JNIEXPORT jint JNICALL Java_android_spectre_Spectre_nativeCalibrateTiming
  (JNIEnv *, jclass, jlong, jint, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
