/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_spectre_Spectre_Callback */

#ifndef _Included_android_spectre_Spectre_Callback
#define _Included_android_spectre_Spectre_Callback
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
