/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_spectre_Spectre */

#ifndef _Included_android_spectre_Spectre
#define _Included_android_spectre_Spectre
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_spectre_Spectre
 * Method:    calibrateTiming
 * Signature: (I[I[I)I
 */
JNIEXPORT jint JNICALL Java_android_spectre_Spectre_calibrateTiming
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     android_spectre_Spectre
 * Method:    read
 * Signature: ([BLandroid/spectre/Spectre/Callback;)V
 */
JNIEXPORT void JNICALL Java_android_spectre_Spectre_read
  (JNIEnv *, jclass, jbyteArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
